Homework10 git
Iliailineya/homeworks pull request #10
Opened 2024-02-28 15:17 UTC by Iliailineya

Implement with controllers: User, account, payments
Implement with services: User, account, payments
Implement with repositories: User, account, payments
Add Exception handlers with controller advice
Additional task:

Implement integration test for controllers

2024-02-29 15:28 UTC, YeaaaaH commented on .gitignore
> +src/main/resources/app.properties
same here

2024-02-29 15:29 UTC, YeaaaaH commented on src/main/java/spring/repository/AccountRepository.java
> +@Repository
remove it

2024-02-29 15:30 UTC, YeaaaaH commented on src/main/java/spring/service/UserService.java
> +        if (repository.existsById(id)) {
you can use  getUserById()

2024-02-29 15:30 UTC, YeaaaaH commented on src/main/java/spring/service/PaymentService.java
> +        if (repository.existsById(id)) {
you can use getPaymentById

2024-02-29 15:31 UTC, YeaaaaH requested changes
small fixs needed

2024-03-01 13:40 UTC, Iliailineya commented on .gitignore
> +src/main/resources/app.properties
done

2024-03-01 13:40 UTC, Iliailineya commented on src/main/java/spring/repository/AccountRepository.java
> +@Repository
done

2024-03-01 13:40 UTC, Iliailineya commented on src/main/java/spring/service/PaymentService.java
> +        if (repository.existsById(id)) {
done

2024-03-01 13:41 UTC, Iliailineya commented on src/main/java/spring/service/UserService.java
> +        if (repository.existsById(id)) {
done

2024-03-01 13:47 UTC, Iliailineya commented
Fixed

2024-03-01 16:03 UTC, YeaaaaH commented on src/main/java/spring/service/PaymentService.java
> +        payment.setId(id);
this line is redundant, if entity is present in db it already has id

2024-03-01 16:03 UTC, YeaaaaH commented on src/main/java/spring/service/UserService.java
> +        user.setId(id);
this line is redundant, if entity is present in db it already has id

2024-03-01 16:04 UTC, YeaaaaH commented on src/main/java/spring/service/AccountService.java
> +        account.setId(id);
this line is redundant, if entity is present in db it already has id

2024-03-01 16:04 UTC, YeaaaaH requested changes
need to fix

2024-03-05 10:41 UTC, Iliailineya commented
Fixed

2024-03-08 14:24 UTC, merged