Homework7 git
Iliailineya/homeworks pull request #6
Opened 2024-02-13 02:03 UTC by Iliailineya

Add hibernate to project

2024-02-13 20:42 UTC, YeaaaaH commented on src/main/resources/app.properties
> +db.password = asSGs#1f$kdfj12sad8
don't share passwords in public

2024-02-13 20:43 UTC, YeaaaaH commented on src/main/java/example/spring/service/AccountService.java
> +import jakarta.transaction.Transactional;
id you use @Transactional annotation it should be from spring package, but it's not needed now

2024-02-13 20:44 UTC, YeaaaaH commented on pom.xml
> +            <groupId>org.springframework.data</groupId>
remove it, no need in spring-data at this moment

2024-02-13 20:44 UTC, YeaaaaH commented on pom.xml
> +            <artifactId>spring-data-commons</artifactId>
remove it, no need in spring-data at this moment

2024-02-13 20:46 UTC, YeaaaaH commented on src/main/java/example/spring/repository/AccountsRepository.java
> +        Session currentSession = sessionFactory.getCurrentSession();
create separate session for each action: create, get, update, delete

2024-02-13 20:48 UTC, YeaaaaH commented on src/main/java/example/spring/repository/AccountsRepository.java
> +        return currentSession.merge(account);
use save()

2024-02-13 20:48 UTC, YeaaaaH requested changes
need to fix comments

2024-02-14 10:43 UTC, Iliailineya commented on src/main/resources/app.properties
> +db.password = asSGs#1f$kdfj12sad8
It was an accident

2024-02-14 13:46 UTC, Iliailineya commented
Fixed

2024-02-15 18:44 UTC, YeaaaaH approved these changes

2024-02-16 11:14 UTC, merged