Homework9 git
Iliailineya/homeworks pull request #9
Opened 2024-02-22 15:26 UTC by Iliailineya

Using liquibase initialize sql schemas and test beanPostProcessor in another module

2024-02-22 18:02 UTC, YeaaaaH commented on TestBean/src/main/java/org/example/bean/RandomValueBeanPostProcessor.java
> +        Field[] fields = bean.getClass().getDeclaredFields();
add check that you obtain needed bean, currently you process it in every bean instead of needed

2024-02-22 18:02 UTC, YeaaaaH requested changes
need to fix

2024-02-23 16:34 UTC, Iliailineya commented
Fixed

2024-02-23 16:51 UTC, YeaaaaH approved these changes

2024-02-23 17:56 UTC, merged